### ISSUE TITLE
Custom `zsh-completions` scripts don't work

### ISSUE THREAD

**Issue by ditsuke** [jotyGill/ezsh#19]
As the title says, custom `zsh-completions` scripts do not work for me unless I call `compinit` again. I've been unable to figure out why this happens. As a workaround, I've added a `compinit` to ezsh's `.zshrc` which works just fine.

**Comment by Locutus64** [comment]
Want to elaborate on this more?

**Comment by ditsuke** [comment]
Sorry, it's been a long time since I used `ezsh`. I'll close this for now.
