### ISSUE TITLE
How do i uninstall this ezsh, given it has messed up my zsh terminal and fonts are weird now.

### ISSUE THREAD

**Issue by lokeshjain2008** [jotyGill/ezsh#27]
Please add steps to uninstall this package. 
If this don't work for the user then it should be easy to go back to the pervious happy life.

**Comment by scottyeung** [comment]
`#!/bin/bash

# Restore the backed up .zshrc
if [ -f ~/.zshrc-backup-* ]; then
mv -f ~/.zshrc-backup-* ~/.zshrc
echo -e "Restored the original .zshrc\n"
else
echo -e "No backup of .zshrc found\n"
fi

# Remove the ezsh configuration directory
if [ -d ~/.config/ezsh ]; then
rm -rf ~/.config/ezsh
echo -e "Removed the ezsh configuration directory\n"
else
echo -e "ezsh configuration directory not found\n"
fi

# Move .zcompdump files back to the home directory
if [ -d ~/.cache/zsh ]; then
mv -f ~/.cache/zsh/.zcompdump* ~/
rm -rf ~/.cache/zsh
echo -e "Moved .zcompdump files back to the home directory\n"
else
echo -e ".zcompdump files not found in ~/.cache/zsh\n"
fi

# Remove the installed fonts
if [ -d ~/.fonts ]; then
rm -f ~/.fonts/HackNerdFont-Regular.ttf
rm -f ~/.fonts/RobotoMonoNerdFont-Regular.ttf
rm -f ~/.fonts/DejaVuSansMNerdFont-Regular.ttf
fc-cache -fv ~/.fonts
echo -e "Removed the installed fonts\n"
else
echo -e "Installed fonts not found in ~/.fonts\n"
fi

# Remove the todo.sh symlink and todo directory
if [ -L ~/.config/ezsh/bin/todo.sh ]; then
rm -f ~/.config/ezsh/bin/todo.sh
rm -rf ~/.config/ezsh/todo
echo -e "Removed the todo.sh symlink and todo directory\n"
else
echo -e "todo.sh symlink not found\n"
fi

# Remove the zsh_history file
if [ -f ~/.zsh_history ]; then
rm -f ~/.zsh_history
echo -e "Removed the zsh_history file\n"
else
echo -e "zsh_history file not found\n"
fi

# Change the default shell back to bash
if chsh -s $(which bash); then
echo -e "Changed the default shell back to bash\n"
else
echo -e "Failed to change the default shell to bash\n"
fi

echo -e "Revert script completed. Please exit the terminal and start a new session.\n"
exit`

**Comment by scottyeung** [comment]
`
#!/bin/bash

# Restore the backed up .zshrc
if [ -f ~/.zshrc-backup-* ]; then
mv -f ~/.zshrc-backup-* ~/.zshrc
echo -e "Restored the original .zshrc\n"
else
echo -e "No backup of .zshrc found\n"
fi

# Remove the ezsh configuration directory
if [ -d ~/.config/ezsh ]; then
rm -rf ~/.config/ezsh
echo -e "Removed the ezsh configuration directory\n"
else
echo -e "ezsh configuration directory not found\n"
fi

# Move .zcompdump files back to the home directory
if [ -d ~/.cache/zsh ]; then
mv -f ~/.cache/zsh/.zcompdump* ~/
rm -rf ~/.cache/zsh
echo -e "Moved .zcompdump files back to the home directory\n"
else
echo -e ".zcompdump files not found in ~/.cache/zsh\n"
fi

# Remove the installed fonts
if [ -d ~/.fonts ]; then
rm -f ~/.fonts/HackNerdFont-Regular.ttf
rm -f ~/.fonts/RobotoMonoNerdFont-Regular.ttf
rm -f ~/.fonts/DejaVuSansMNerdFont-Regular.ttf
fc-cache -fv ~/.fonts
echo -e "Removed the installed fonts\n"
else
echo -e "Installed fonts not found in ~/.fonts\n"
fi

# Remove the todo.sh symlink and todo directory
if [ -L ~/.config/ezsh/bin/todo.sh ]; then
rm -f ~/.config/ezsh/bin/todo.sh
rm -rf ~/.config/ezsh/todo
echo -e "Removed the todo.sh symlink and todo directory\n"
else
echo -e "todo.sh symlink not found\n"
fi

# Remove the zsh_history file
if [ -f ~/.zsh_history ]; then
rm -f ~/.zsh_history
echo -e "Removed the zsh_history file\n"
else
echo -e "zsh_history file not found\n"
fi

# Change the default shell back to bash
if chsh -s $(which bash); then
echo -e "Changed the default shell back to bash\n"
else
echo -e "Failed to change the default shell to bash\n"
fi

echo -e "Revert script completed. Please exit the terminal and start a new session.\n"
exit
`

**Comment by jotyGill** [comment]
As the Readme outlines the fonts requirement:
`If the text/icons look broken, make sure your terminal is using one of the Nerd fonts. https://github.com/powerline/fonts/issues/185. I recommend "RobotoMono Nerd Font"`

To uninstall simply delete ~/.zshrc and ~/.config/ezsh/. The script creates a backup of your original .zshrc in the home folder with the filename indicating it's a backup. Rename it back.
