### ISSUE TITLE
Unable to add personal config

### ISSUE THREAD

**Issue by ak4zh** [jotyGill/ezsh#34]
After I add any personal config I get this error when restarting terminal and the om-my-zsh does not work anymore until I delete the personal config file and restart the terminal.

I just added the example config `personal_rc.zsh` in `~/.config/ezsh/zshrc/`

```bash
~/.zshrc:18: no matches found: ~/.config/ezsh/zshrc/.*
```

**Comment by HoBeom** [comment]
I think we should modify ~/.zshrc as below

```
if [ "$(ls -A $ZSH_CONFIGS_DIR)" ]; then
    for file in "$ZSH_CONFIGS_DIR"/*.zsh; do # only include .zsh files
        # Exclude '.' and '..' from being sourced
        if [ -f "$file" ]; then
            source "$file"
        fi
    done
fi
```
